### ISSUE TITLE
The save file's name is too long.

### ISSUE THREAD

**Issue by leoxxx** [libretro/beetle-ngp-libretro#104]
I found the save file's name format has been changed.
Before: Rom's name.
Now: Zip file's name # Rom's name.
It's too long.

**Comment by Sanaki** [comment]
Just came to report this same thing. I'm not sure what's causing this, but it's specific to this core. Appending the archive name is an issue that needs resolving.

**Comment by Sanaki** [comment]
Looks like this started representing in the core based on a frontend change, not a core change. It'll still require fixing in the core though. First bad commit was libretro/RetroArch@334a43a7c5b072d468b8cb4d6b4d1737795d12e3.
