### ISSUE TITLE
Core Fails To Remove Temporarily Extracted ROMs on Exit

### ISSUE THREAD

**Issue by Awakened0** [libretro/beetle-ngp-libretro#16]
On Windows the latest nightly build of this core leaves behind extracted ROMs after exiting. RetroArch seems to exit cleanly and save SRAM fine according to the log. Here are the lines where it mentions the failure:

RetroArch [INFO] :: Removing temporary content file: ....\Games\SNK Neo Geo Pocket Color\Dark Arms - Beast Buster 1999 (World) (En,Ja).ngc.
RetroArch [ERROR] :: Failed to remove temporary file: ....\Games\SNK Neo Geo Pocket Color\Dark Arms - Beast Buster 1999 (World) (En,Ja).ngc.

Full log here: http://hastebin.com/enasudexab.tex

I have an older build of the core from 2015-7-17 that cleans up the temp file fine.

**Comment by fr500** [comment]
I think it's retroarch failing not the core itself, can you make sure to test both cores in the same RA version?

logs from the core read RetroArch [libretro INFO]

**Comment by Awakened0** [comment]
Yes, I tested both in the same RA version, so I figured it was something in the core. I tried the latest core with both today's nightly and one from 2016-01-06 and both leave a temp file behind. With the older build of the core in each RA version neither leave anything behind.

**Comment by fr500** [comment]
Pretty weird...

**Comment by Jacklaleyn** [comment]
any posible soution? same problem here

**Comment by klepp0906** [comment]
mine does this as well.  While not the ideal solution you can set the directory to the windows temp folder ;p

I use symlinks to manage alot of stuff without using additional space and the fact this was extracting and leaving remnants in the symlink only folders meant i was gaining not saving space ;p
