### ISSUE TITLE
Suggest Mednafen NeoPop create a folder in save directory

### ISSUE THREAD

**Issue by leoxxx** [libretro/beetle-ngp-libretro#50]
The save file in the save rootdirectory. Not like fba, create a folder and save file in the folder.
I suggest it create a folder in save directory.

**Comment by fr500** [comment]
No need, RA has an option for that
Use the frontend option

![image](https://user-images.githubusercontent.com/1721040/50553611-2baede00-0c78-11e9-99df-03da1df3c421.png)
