### ISSUE TITLE
[Regression] Flickering When In Menu or Paused

### ISSUE THREAD

**Issue by Awakened0** [libretro/beetle-ngp-libretro#54]
When you bring up the XMB or Ozone menu, the paused gameplay behind it flickers. It seems to flicker/glitch a little when you press P to pause too. Happens under GL and Vulkan. The previous version of the core I was using (b9fff92) doesn't have this issue.

**Comment by stellarporter** [comment]
Problem in a shellfish explanation. Core sends RGB555 format to frontend. Pause to menu. Frontend converts to 565 frame1 = good colors. Frontend treats raw 555 pixel (??) as 565 frame2 = highly washed out. Alternate.


There's 2 points where this flag FRONTEND_SUPPORTS_RGB565 is not compiling:
https://github.com/libretro/beetle-ngp-libretro/blob/555e292e38f41b1e401727af9e5d08a8c146a714/libretro.cpp#L482

https://github.com/libretro/beetle-ngp-libretro/blob/4ea4d9f9f6d32abc3148f68ad7efaaa16ebaeeb3/mednafen/video.h#L6


And original source of problem.
https://github.com/libretro/beetle-ngp-libretro/blob/master/Makefile.common

I don't want to break cross-compiler by editing this myself, but I did force solution and works. Help from repo maintainers?

**Comment by retro-wertz** [comment]
since PR after the specified good commit are done by me, i dont see anything related that could have caused some issues in during game pause.. but lets see...

**Comment by stellarporter** [comment]
Nice catch!

**Comment by Awakened0** [comment]
Thanks ya'll!
