### ISSUE TITLE
Suggestion: use the zipped files'name as battery save files's name.

### ISSUE THREAD

**Issue by leoxxx** [libretro/beetle-ngp-libretro#62]
Now is the unzipped file's name.

**Comment by fr500** [comment]
No, it can't be done, it doesn't know the zip's filename and it's such a niche request I don't see the point.

**Comment by leoxxx** [comment]
> 
> 
> No, it can't be done, it doesn't know the zip's filename and it's such a niche request I don't see the point.

Are you sure? I know other core is use the zipped files' name(like fba and so on). But why the Neopop and NGP.EMU can? And what's the "niche" meaning?
For example, King of Fighters R2.ngp, I name the zipfile name "KOF R2.zip", So battery save file's name=KOF R2.flash. But now is King of Fighters R2.flash.

**Comment by fr500** [comment]
Those cores load the archive not the file inside the archive, those cores
support ZIP directly.

**Comment by leoxxx** [comment]
So your meaning is this core not support zip, right?  It load zip must extract to a temp folder. (I guess)

**Comment by fr500** [comment]
Most cores don't because there is no point.

**Comment by leoxxx** [comment]
I don't think so. It make the save name match with the zip name. Why can the state save's name use the zip name?

**Comment by retro-wertz** [comment]
there is no point in doing such a  thing...

**Comment by fr500** [comment]
Basically you want RA tailored to your weird usecase.

There is no point really.
