### ISSUE TITLE
Building libretro core with SDL audio

### ISSUE THREAD

**Issue by Tommy9toes** [libretro/beetle-ngp-libretro#83]
I've successfully built the core as far as I can tell for Steamlink hardware but it defaults to Alsa audio.

I've found documentation on changing mednafen.cfg from default to sdl for the audio, but it doesn't look like it's an existing file for the libretro build.

Using Alsa isn't an option without access to the firmware of the device. In short, I was wondering if there was a way to force SDL audio.

**Comment by newsie-oss** [comment]
The cores seem to have zero control over the audio driver itself. They just send a stream of 16-bit stereo samples to the frontend and let that layer handle the messy audio, video stuff.

So I think it's a frontend Retroarch app issue. There is a "drivers" tab that'll let you select the audio driver you want. For windows, it says: xaudio, dsound, wsapi, null. Maybe something similar can be done for your hardware? Or just compile Retroarch with SDL2 only and somehow exclude Alsa?

**Comment by Tommy9toes** [comment]
I think this can be closed and I have other issues. I was able to get it forced to SDL with a config on the command line. It fails and it tries Alsa which also fails. I'll go back and check on my build options and see if I can do anything there. Thanks for the help.
