### ISSUE TITLE
After the update to 1.23.0 no longer works on Wiiu 

### ISSUE THREAD

**Issue by ruijtunes** [libretro/beetle-ngp-libretro#84]
After the update to 1.23.0 this core no longer works on Wiiu

Commits on Nov 8, 2019 - 432cb01
Merge pull request #73 from f21red/update to 1.23.0
@hizzlekizzle

The core doesn't crash but the games don't initialize properly, hanging with a pink screen.

**Comment by newsie-oss** [comment]
Do the core logs print anything? That sounds like an issue with loading the rom header...

**Comment by ruijtunes** [comment]
In attach are the log files. I don't see any error:

[retroarch__2020_01_01__15_36_01.log](https://github.com/libretro/beetle-ngp-libretro/files/4014214/retroarch__2020_01_01__15_36_01.log)
[retroarch__2020_01_01__15_37_01.log](https://github.com/libretro/beetle-ngp-libretro/files/4014215/retroarch__2020_01_01__15_37_01.log)

**Comment by newsie-oss** [comment]
Gee, that is weird. My log has something like this, which tells me that the core at least tried to load something.
```[libretro INFO] Name:    METALSLUG2ND
[libretro INFO] System:  
[libretro INFO] Color
[libretro INFO] 
[libretro INFO] Catalog:  97 (sub 4)
[libretro INFO] Starting PC:  0x20004B
[libretro INFO] ROM:       4096KiB
```

**Comment by ruijtunes** [comment]
I tried again, Here are the output:

[libretro INFO] Name:    METALSLUG2ND
[libretro INFO] System:  
[libretro INFO] Color
[libretro INFO] 
[libretro INFO] Catalog:  24832 (sub 4)
[libretro INFO] Starting PC:  0x002000
[libretro INFO] ROM:       4096KiB
[libretro INFO] MDFN_MakeFName: sd:/retroarch/cores/savefiles/Metal Slug - 2nd Mission (World) (En,Ja).flash
[retroarch__2020_01_01__22_57_07.log](https://github.com/libretro/beetle-ngp-libretro/files/4014652/retroarch__2020_01_01__22_57_07.log)

**Comment by newsie-oss** [comment]
Definitely a byteswapping issue. I think the endian conversion got botched. If you can compile your own code, please try this change:
https://github.com/libretro/beetle-ngp-libretro/edit/master/mednafen/mednafen-endian.h
```
static INLINE uint32 MDFN_de32lsb(const uint8 *morp)
{
#ifdef MSB_FIRST
  return(morp[3]|(morp[2]<<8)|(morp[1]<<16)|(morp[0]<<24));
#else
  return(morp[0]|(morp[1]<<8)|(morp[2]<<16)|(morp[3]<<24));
#endif
}
```

**Comment by ruijtunes** [comment]
Sorry I can't compile it myself.

If you send me a rpx I can test it.
Thanks

**Comment by tailshine** [comment]
That fix doesn't sound correct. MSB endian is important when we're accessing 2/4/8 bytes from memory. Code snippet says (uint8) 8-bit = 1 byte. Endian-ness shouldn't matter here; always reading bytes in correct order.

If it was uint16, uint32, uint64 then we'd have to reverse the bytes in CPU registers.

```
static INLINE uint16 MDFN_de16lsb(const uint8 *morp)
{
  return morp[0] | (morp[1]<<8);
}

static INLINE uint32 MDFN_de32lsb(const uint8 *morp)
{
  return morp[0] | (morp[1]<<8) | (morp[2]<<16) | (morp[3]<<24);
}
```

I'll try compiling a build later.

**Comment by tailshine** [comment]
Try this Wii U build
https://github.com/tailshine/beetle-ngp-libretro/blob/wiiu/mednafen_ngp_libretro.7z?raw=true

**Comment by ruijtunes** [comment]
It’s working fine with this build. 👍

**Comment by tailshine** [comment]
One more test build before PR submission.
https://github.com/tailshine/beetle-ngp-libretro/blob/wiiu/mednafen_ngp_libretro_2.7z?raw=true


I receive 25% speed increase on little-endian system. Power PC devices should receive considerable boost also.
https://en.wikipedia.org/wiki/List_of_PowerPC-based_game_consoles

**Comment by ruijtunes** [comment]
I tested this latest version of ngp core  and it works fine.

I have the same problem with vb core after the update to 1.23.0
[libretro INFO] Title:     
[libretro INFO] Game ID Code: 1447707205
[libretro INFO] Manufacturer Code: 17730
[libretro INFO] Version:   0
[libretro INFO] ROM:       1024KiB
[libretro INFO] 
[libretro INFO] V810 Emulation Mode: Accurate
[libretro INFO] (null)

The WonderSwan core Works.

**Comment by tailshine** [comment]
Thanks for the info. Submitted ngp and wswan (there's some joypad and savestate endian-ness). Will look into vb also.

**Comment by trioan** [comment]
Is this core broken on Wii U or has it been fixed up??

**Comment by ruijtunes** [comment]
Has been working well. It was resolved.

**Comment by trioan** [comment]
Oh, nice. Would someone mind closing the issue?
