### ISSUE TITLE
[Wii Feature Request] Wiiflow Lite plugin

### ISSUE THREAD

**Issue by Edu789** [libretro/beetle-ngp-libretro#92]
The core freeintv don't work as Wiiflow plugins, when entering the game he goes back to the Wiiflow Lite menu...

**Comment by trioan** [comment]
freeintv = Intellivision. This is the Neo Geo Pocket core. Wrong ticket?

**Comment by Edu789** [comment]
I was wrong, it's the Neo Geo Pocket core and not Intellivision's...
